### PR TITLE
Replace empty embed field arrays with null after serialization

### PR DESCRIPTION
**Pull request by helightdev**
Creating an embed with the message builder results, in the raw embed always having an empty array of fields instead of null in its final payload, which adds unnecessary spacing at the end of the embed if no fields are specified.

This image shows how it should look based on the code vs how it actually looks.
guilded_image_f9fc0637776c5648ca66ec23a9619145

To solve this issue, is just check the array length of the serialized embed and replace it with null incase the array is empty.

### CODE REVIEW

**Comment by helightdev** [comment]
Already tested it using my local setup and everything seems to work as expected.

**Comment by helightdev** [comment]
Closed in favour of @SrGaabriel solution https://www.guilded.gg/API-Official/groups/53NVy4j3/channels/bda8781d-df7d-4c6b-ae0a-6f3c428dacf3/chat?messageId=e2f3adaa-b39c-4610-a057-6112ad62e883

**Comment by helightdev** [comment]
Tests it and it still works so this should be fine now

**Review by SrGaabriel — APPROVED** [review]
LGTM!

**Pull request merged**
